// @index(['./**/*.ts', /(test|spec)/g], f => `export * from '${f.path}'`)
export * from "./CheckQuizAnswer/CheckQuizAnswer"
export * from "./CreateDiscipline/CreateDiscipline"
export * from "./CreateQuestion/CreateQuestion"
export * from "./CreateQuiz/CreateQuiz"
export * from "./CreateQuizAnswer/CreateQuizAnswer"
export * from "./CreateUser/CreateUser"
export * from "./DeleteDiscipline/DeleteDiscipline"
export * from "./GetDisciplineById/GetDisciplineById"
export * from "./GetDisciplineByName/GetDisciplineByName"
export * from "./GetDisciplines/GetDisciplines"
export * from "./GetLearning/GetLearning"
export * from "./GetNextQuestion/GetNextQuestion"
export * from "./GetQuestionById/GetQuestionById"
export * from "./GetQuestions/GetQuestions"
export * from "./GetQuizById/GetQuizById"
export * from "./GetQuizzes/GetQuizzes"
export * from "./GetUserByEmail/GetUserByEmail"
export * from "./GetUserById/GetUserById"
export * from "./GetUsers/GetUsers"
export * from "./LoginUser/LoginUser"
export * from "./LogoutUser/LogoutUser"
export * from "./UpdateDiscipline/UpdateDiscipline"
// @endindex
